version: "3.9"

services:
  app:
    image: ghcr.io/remla23-team7/app:latest
    depends_on:
      - service
    ports:
      - "80:80"

  service:
    image: ghcr.io/remla23-team7/model-service:latest
    depends_on:
      - training
    ports:
      - "5000:5000"

  training:
    image: ghcr.io/remla23-team7/model-training:0.0.1
